name: Build and Deploy Java App to Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t java-k8s-app:latest .

    - name: Save Docker image as tar
      run: docker save java-k8s-app:latest -o java-k8s-app.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-k8s-app-image
        path: java-k8s-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: java-k8s-app-image

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start --driver=docker
        eval $(minikube -p minikube docker-env)

    - name: Load image into Minikube
      run: |
        docker load -i java-k8s-app.tar

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl get pods
        kubectl get svc

